module Monopoly
  module Coordinates
    # Window
    TOP_Y = 0
    BOTTOM_Y = ENV['RESOLUTION_HEIGHT'].to_i
    LEFT_X = 0
    RIGHT_X = ENV['RESOLUTION_WIDTH'].to_i
    CENTER_X = RIGHT_X / 2
    CENTER_Y = BOTTOM_Y / 2

    # Dialogue box
    DIALOGUE_BOX_TOP_Y = CENTER_Y - 150
    DIALOGUE_BOX_BOTTOM_Y = CENTER_Y + 150
    DIALOGUE_BOX_LEFT_X = CENTER_X - 300
    DIALOGUE_BOX_RIGHT_X = CENTER_X + 300
    DIALOGUE_BOX_HEIGHT = DIALOGUE_BOX_BOTTOM_Y - DIALOGUE_BOX_TOP_Y
    DIALOGUE_BOX_WIDTH = DIALOGUE_BOX_RIGHT_X - DIALOGUE_BOX_LEFT_X

    # Tile menu
    TILE_HEIGHT = 658
    TILE_WIDTH = 400
    THUMBNAIL_HEIGHT = TILE_WIDTH / 10

    FIRST_HOUSE_BUTTON_X = CENTER_X + 210
    FIRST_HOUSE_BUTTON_Y = CENTER_Y - 315

    BACK_TO_CURRENT_TILE_BUTTON_X = CENTER_X + 240
    BACK_TO_CURRENT_TILE_BUTTON_Y = CENTER_Y + 300

    TILE_OWNER_TOKEN_X = CENTER_X - 260
    TILE_OWNER_TOKEN_Y = CENTER_Y - 265

    BUY_BUTTON_X = TILE_OWNER_TOKEN_X
    BUY_BUTTON_Y = TILE_OWNER_TOKEN_Y

    MORTGAGE_LOCK_X = CENTER_X - 290
    MORTGAGE_LOCK_Y = CENTER_Y + 220

    # Action menu
    ACTION_MENU_TOP_Y = BOTTOM_Y - (THUMBNAIL_HEIGHT * 11) - 30
    ACTION_MENU_BOTTOM_Y = BOTTOM_Y
    ACTION_MENU_LEFT_X = RIGHT_X - (THUMBNAIL_HEIGHT * 11) - 30
    ACTION_MENU_RIGHT_X = RIGHT_X
    ACTION_MENU_HEIGHT = ACTION_MENU_BOTTOM_Y - ACTION_MENU_TOP_Y
    ACTION_MENU_WIDTH = ACTION_MENU_RIGHT_X - ACTION_MENU_LEFT_X

    # Player menu
    PLAYER_MENU_TOP_Y = BOTTOM_Y - 375
    PLAYER_MENU_BOTTOM_Y = BOTTOM_Y
    PLAYER_MENU_LEFT_X = LEFT_X
    PLAYER_MENU_RIGHT_X = LEFT_X + 500
    PLAYER_MENU_HEIGHT = PLAYER_MENU_BOTTOM_Y - PLAYER_MENU_TOP_Y
    PLAYER_MENU_WIDTH = PLAYER_MENU_RIGHT_X - PLAYER_MENU_LEFT_X

    # Group menu
    GROUP_MENU_TOP_Y = CENTER_Y - 400
    GROUP_MENU_BOTTOM_Y = CENTER_Y + 400
    GROUP_MENU_LEFT_X = CENTER_X - 800
    GROUP_MENU_RIGHT_X = CENTER_X + 800
    GROUP_MENU_HEIGHT = GROUP_MENU_BOTTOM_Y - GROUP_MENU_TOP_Y
    GROUP_MENU_WIDTH = GROUP_MENU_RIGHT_X - GROUP_MENU_LEFT_X
    GROUP_MENU_BORDER_WIDTH = 8

    # Deed menu
    DEED_MENU_TOP_Y = CENTER_Y - 400
    DEED_MENU_BOTTOM_Y = CENTER_Y + 400
    DEED_MENU_LEFT_X = CENTER_X - 400
    DEED_MENU_RIGHT_X = CENTER_X + 400
    DEED_MENU_HEIGHT = DEED_MENU_BOTTOM_Y - DEED_MENU_TOP_Y
    DEED_MENU_WIDTH = DEED_MENU_RIGHT_X - DEED_MENU_LEFT_X
    DEED_MENU_BORDER_WIDTH = 8

    # Error dialogue
    ERROR_DIALOGUE_TOP_Y = TOP_Y + 25
    ERROR_DIALOGUE_BOTTOM_Y = TOP_Y + 175
    ERROR_DIALOGUE_LEFT_X = CENTER_X - 250
    ERROR_DIALOGUE_RIGHT_X = CENTER_X + 250
    ERROR_DIALOGUE_HEIGHT = ERROR_DIALOGUE_BOTTOM_Y - ERROR_DIALOGUE_TOP_Y
    ERROR_DIALOGUE_WIDTH = ERROR_DIALOGUE_RIGHT_X - ERROR_DIALOGUE_LEFT_X
    ERROR_DIALOGUE_BORDER_WIDTH = 8

    # Event history menu
    EVENT_HISTORY_MENU_TOP_Y = CENTER_Y - 500
    EVENT_HISTORY_MENU_BOTTOM_Y = CENTER_Y + 500
    EVENT_HISTORY_MENU_LEFT_X = CENTER_X - 600
    EVENT_HISTORY_MENU_RIGHT_X = CENTER_X + 600
    EVENT_HISTORY_MENU_HEIGHT = EVENT_HISTORY_MENU_BOTTOM_Y - EVENT_HISTORY_MENU_TOP_Y
    EVENT_HISTORY_MENU_WIDTH = EVENT_HISTORY_MENU_RIGHT_X - EVENT_HISTORY_MENU_LEFT_X
    EVENT_HISTORY_MENU_BORDER_WIDTH = 8

    # Player inspector
    PLAYER_INSPECTOR_TOP_Y = CENTER_Y - 400
    PLAYER_INSPECTOR_BOTTOM_Y = CENTER_Y + 400
    PLAYER_INSPECTOR_LEFT_X = CENTER_X - 400
    PLAYER_INSPECTOR_RIGHT_X = CENTER_X + 400
    PLAYER_INSPECTOR_HEIGHT = PLAYER_INSPECTOR_BOTTOM_Y - PLAYER_INSPECTOR_TOP_Y
    PLAYER_INSPECTOR_WIDTH = PLAYER_INSPECTOR_RIGHT_X - PLAYER_INSPECTOR_LEFT_X
    PLAYER_INSPECTOR_BORDER_WIDTH = 8

    # Player list menu
    PLAYER_LIST_MENU_TOP_Y = CENTER_Y - 200
    PLAYER_LIST_MENU_BOTTOM_Y = CENTER_Y + 200
    PLAYER_LIST_MENU_LEFT_X = CENTER_X - 925
    PLAYER_LIST_MENU_RIGHT_X = CENTER_X + 925
    PLAYER_LIST_MENU_HEIGHT = PLAYER_LIST_MENU_BOTTOM_Y - PLAYER_LIST_MENU_TOP_Y
    PLAYER_LIST_MENU_WIDTH = PLAYER_LIST_MENU_RIGHT_X - PLAYER_LIST_MENU_LEFT_X
    PLAYER_LIST_MENU_BORDER_WIDTH = 8

    COMPASS_TOP_Y = TOP_Y + 5

    MAP_MENU_CENTER_Y = CENTER_Y + 200
    MAP_MENU_TILE_CENTER_Y = MAP_MENU_CENTER_Y - 340
    MAP_MENU_TILE_HEIGHT = 620
    MAP_MENU_TILE_WIDTH = 710
  end
end
