module Monopoly
  module Coordinates
    TOP_Y = 0
    BOTTOM_Y = 1080
    LEFT_X = 0
    RIGHT_X = 1920
    CENTER_X = 960
    CENTER_Y = 540

    DIALOGUE_BOX_TOP_Y = 390
    DIALOGUE_BOX_BOTTOM_Y = 690
    DIALOGUE_BOX_LEFT_X = 660
    DIALOGUE_BOX_RIGHT_X = 1260
    DIALOGUE_BOX_HEIGHT = DIALOGUE_BOX_BOTTOM_Y - DIALOGUE_BOX_TOP_Y
    DIALOGUE_BOX_WIDTH = DIALOGUE_BOX_RIGHT_X - DIALOGUE_BOX_LEFT_X

    INSPECTOR_TOP_Y = 275
    INSPECTOR_BOTTOM_Y = 965
    INSPECTOR_LEFT_X = 480
    INSPECTOR_RIGHT_X = 1440
    INSPECTOR_HEIGHT = INSPECTOR_BOTTOM_Y - INSPECTOR_TOP_Y
    INSPECTOR_WIDTH = INSPECTOR_RIGHT_X - INSPECTOR_LEFT_X

    BUTTON_1_X = RIGHT_X - Button::DEFAULT_WIDTH
    BUTTON_1_Y = BOTTOM_Y - Button::DEFAULT_HEIGHT
    BUTTON_2_X = RIGHT_X - Button::DEFAULT_WIDTH
    BUTTON_2_Y = BOTTOM_Y - (Button::DEFAULT_HEIGHT * 2 + 1)
  end
end
