module Monopoly
  module Coordinates
    TOP_Y = 0
    BOTTOM_Y = ENV['RESOLUTION_HEIGHT'].to_i
    LEFT_X = 0
    RIGHT_X = ENV['RESOLUTION_WIDTH'].to_i
    CENTER_X = RIGHT_X / 2
    CENTER_Y = BOTTOM_Y / 2

    DIALOGUE_BOX_TOP_Y = CENTER_Y - 150
    DIALOGUE_BOX_BOTTOM_Y = CENTER_Y + 150
    DIALOGUE_BOX_LEFT_X = CENTER_X - 300
    DIALOGUE_BOX_RIGHT_X = CENTER_X + 300
    DIALOGUE_BOX_HEIGHT = DIALOGUE_BOX_BOTTOM_Y - DIALOGUE_BOX_TOP_Y
    DIALOGUE_BOX_WIDTH = DIALOGUE_BOX_RIGHT_X - DIALOGUE_BOX_LEFT_X

    BUTTON_1_X = RIGHT_X - 275#Button::DEFAULT_WIDTH
    BUTTON_1_Y = BOTTOM_Y - 50#Button::DEFAULT_HEIGHT
    BUTTON_2_X = RIGHT_X - 275#Button::DEFAULT_WIDTH
    BUTTON_2_Y = BOTTOM_Y - (50 * 2 + 1)#(Button::DEFAULT_HEIGHT * 2 + 1)

    FIRST_HOUSE_BUTTON_X = CENTER_X + 210
    FIRST_HOUSE_BUTTON_Y = CENTER_Y - 315

    BACK_TO_CURRENT_TILE_BUTTON_X = CENTER_X + 250
    BACK_TO_CURRENT_TILE_BUTTON_Y = CENTER_Y + 300

    TILE_OWNER_TOKEN_X = CENTER_X - 260
    TILE_OWNER_TOKEN_Y = CENTER_Y - 265

    BUY_BUTTON_X = TILE_OWNER_TOKEN_X
    BUY_BUTTON_Y = TILE_OWNER_TOKEN_Y

    MORTGAGE_LOCK_X = CENTER_X - 290
    MORTGAGE_LOCK_Y = CENTER_Y + 220

    GROUP_MENU_TOP_Y = CENTER_Y - 400
    GROUP_MENU_BOTTOM_Y = CENTER_Y + 400
    GROUP_MENU_LEFT_X = CENTER_X - 800
    GROUP_MENU_RIGHT_X = CENTER_X + 800
    GROUP_MENU_HEIGHT = GROUP_MENU_BOTTOM_Y - GROUP_MENU_TOP_Y
    GROUP_MENU_WIDTH = GROUP_MENU_RIGHT_X - GROUP_MENU_LEFT_X
    GROUP_MENU_BORDER_WIDTH = 8
    GROUP_MENU_TILE_BUTTON_HEIGHT = (GROUP_MENU_HEIGHT - (GROUP_MENU_BORDER_WIDTH * 2)) * 0.75
    GROUP_MENU_TILE_BUTTON_WIDTH = GROUP_MENU_TILE_BUTTON_HEIGHT * 0.6
    GROUP_MENU_TILE_GAP = GROUP_MENU_TILE_BUTTON_WIDTH * 0.04
    GROUP_MENU_FIRST_TILE_X = CENTER_X - (GROUP_MENU_TILE_GAP * 1.5) - (GROUP_MENU_TILE_BUTTON_WIDTH * 2)
    GROUP_MENU_FIRST_TILE_ALT_X_OFFSET = (GROUP_MENU_TILE_GAP + GROUP_MENU_TILE_BUTTON_WIDTH) * 0.5
    GROUP_MENU_FIRST_TILE_Y = GROUP_MENU_TOP_Y + GROUP_MENU_BORDER_WIDTH + 50

    DEED_MENU_TOP_Y = CENTER_Y - 400
    DEED_MENU_BOTTOM_Y = CENTER_Y + 400
    DEED_MENU_LEFT_X = CENTER_X - 400
    DEED_MENU_RIGHT_X = CENTER_X + 400
    DEED_MENU_HEIGHT = DEED_MENU_BOTTOM_Y - DEED_MENU_TOP_Y
    DEED_MENU_WIDTH = DEED_MENU_RIGHT_X - DEED_MENU_LEFT_X
    DEED_MENU_BORDER_WIDTH = 8
    DEED_HEIGHT = (Coordinates::DEED_MENU_HEIGHT - (Coordinates::DEED_MENU_BORDER_WIDTH * 2)) * 0.9
    DEED_WIDTH = (Coordinates::DEED_MENU_WIDTH - (Coordinates::DEED_MENU_BORDER_WIDTH * 2)) * 0.6
  end
end
